clip:
  vision_model: "ViT-B/32"
  model_id: "openai/clip-vit-base-patch32"

data:
  zillow_root: /zillow_graph_csv
  coco_root: "/coco"
  coco_partition: "val2017"

training:
  batch_size: 1024
  learning_rate: 0.0005

model:
  n_layers: 3
  hidden_dim: 256
  sage_conv_method: 'mean'
  dropout: 0