model:
  n_layers: 3
  hidden_dim: 512
  sage_conv_method: 'mean'
  dropout: 0.2

training:
  batch_size: 1024
  learning_rate: 0.05
  n_epochs: 5

coco:
  root: "../../coco"
  partition: "train2017"
  batch_size: 512
  num_workers: 8

clip:
  vision_model: "ViT-B/32"
  model_id: "openai/clip-vit-base-patch32"

data:
  zillow_data_root: 'data/zillow_data'
  zillow_graph_root: 'graph/zillow_graph_csv'
  zillow_verified_data_root: 'data/zillow_verified_data'
  zillow_verified_graph_root: 'graph/zillow_verified_graph_csv'
  coco_graph_root: 'graph/coco_graph_csv'
  coco_data_root: 'data/coco_data'
  coco_partition: "val2017"
  zillow: 
    path: data/zillow_data
    image_embeds: 'data/zillow_data/image_embed.joblib'
    keyword_embeds: 'data/zillow_data/keyword_embed.joblib'
    scene_embeds: 'data/zillow_data/scene_embed.joblib'
    connections: 'data/zillow_data/NYU_photoboard_file.csv'
  mscoco:
    path: data/coco_data
    partition: "val2017"
    image_embeds: 'data/coco_data/coco_image_embeddings.pt'
    keyword_embeds: 'data/coco_data/coco_tag_embeddings.pt'
    connections: 'data/coco_data/image_text_data.csv'
  zillow_verified:
    path: data/zillow_verified_data
    image_embeds: data/zillow_verified_data/object_detect_image_embed.joblib
    keyword_embeds: data/zillow_verified_data/object_detect_keyword_embed.joblib  
    scene_embeds: data/zillow_verified_data/object_detect_scene_embed.joblib
    connections: data/zillow_verified_data/nyu_object_dataset.csv

graph:
  zillow:
    dataset_name: 'zillow_graph'
    graph_dir: 'graph/zillow_graph_csv'
    edges: 'zillow_edges.csv'
    nodes: 'zillow_nodes.csv'
  mscoco:
    dataset_name: 'coco_graph'
    graph_dir: 'graph/coco_graph_csv'
    edges: 'coco_edges.csv'
    nodes: 'coco_nodes.csv'
  zillow_verified:
    dataset_name: 'zillow_verified_graph'
    graph_dir: 'graph/zillow_verified_graph_csv'
    edges: 'zillow_verified_edges.csv'
    nodes: 'zillow_verified_nodes.csv'