model:
  n_layers: 3
  hidden_dim: 512
  sage_conv_method: 'mean'
  dropout: 0

coco:
  root: "../../coco"
  partition: "train2017"
  batch_size: 512
  num_workers: 8

clip:
  vision_model: "ViT-B/32"
  model_id: "openai/clip-vit-base-patch32"

data:
  zillow_root: 'graph/zillow_graph_csv'
  coco_graph_root: "graph/coco_graph_csv"
  coco_root: 'coco_csv'
  coco_partition: "val2017"
  zillow: 
    path: data/zillow/zillow_graph_csv
    image_embeds: '../../zillow_data/image_embed.joblib'
    keyword_embeds: '../../zillow_data/keyword_embed.joblib'
    scene_embeds: '../../zillow_data/scene_embed.joblib'
    connections: '../../zillow_data/NYU_photoboard_file.csv'
  mscoco:
    path: "/coco"
    partition: "val2017"
    image_embeds: '../../coco/coco_image_embeddings.pt'
    keyword_embeds: '../../coco/coco_tag_embeddings.pt'
    connections: '../../coco/image_text_data.csv'

graph:
  zillow:
    dataset_name: 'zillow_graph'
    graph_dir: '../../graph/zillow_graph_csv/'
    edges: 'zillow_edges.csv'
    nodes: 'zillow_nodes.csv'
  mscoco:
    dataset_name: 'coco_graph'
    graph_dir: '../../graph/coco_graph_csv/'
    edges: 'coco_edges.csv'
    nodes: 'coco_nodes.csv'

training:
  batch_size: 1024
  learning_rate: 0.00005

