coco:
  root: "../../coco"
  partition: "val2017"
  batch_size: 1024
  num_workers: 8

clip:
  vision_model: "ViT-B/32"
  model_id: "openai/clip-vit-base-patch32"

data:
  zillow: 
    image_embeds: '../../zillow_data/image_embed.joblib'
    keyword_embeds: '../../zillow_data/keyword_embed.joblib'
    scene_embeds: '../../zillow_data/scene_embed.joblib'
    connections: '../zillow_data/NYU_photoboard_file.csv'
  mscoco:
    image_embeds: '../../coco/coco_image_embeddings.pt'
    keyword_embeds: '../../coco/coco_tag_embeddings.pt'
    connections: '../../coco/image_text_data.csv'

graph:
  zillow:
    dataset_name: 'zillow_graph'
    graph_dir: '../../graph/zillow_graph_csv/'
    edges: 'zillow_edges.csv'
    nodes: 'zillow_nodes.csv'
  mscoco:
    dataset_name: 'coco_graph'
    graph_dir: '../../graph/coco_graph_csv/'
    edges: 'coco_edges.csv'
    nodes: 'coco_nodes.csv'